name: Build and Publish Oasis Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oasis repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build backend and frontend and push Oasis Docker images
        run: |
          git fetch --tags
          LAST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo 'REACT_APP_BACKEND_URI='                                 >  frontend/.env
          echo 'REACT_APP_AUTH_TYPE="BASIC"'                           >> frontend/.env
          echo "REACT_APP_VERSION=\"`git describe --tags --abbrev=0` (`git symbolic-ref --short HEAD`, `git describe --always`)\"" >> frontend/.env
          echo 'REACT_APP_GTM_ID="G-FZQWZ6HET9"'                       >> frontend/.env
          cd frontend && docker buildx build -f Dockerfile --push --tag ghcr.io/oasisdefender/oasis-frontend-${GITHUB_REF#refs/heads/}:$LAST_TAG .
          cd ../backend  && docker buildx build -f Dockerfile --push --tag ghcr.io/oasisdefender/oasis-backend-${GITHUB_REF#refs/heads/}:$LAST_TAG .


