name: Build and Publish Oasis Docker Image

#on:
#  push:
#    branches:
#      - main
on:
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout oasis repo
        uses: actions/checkout@v2

      - name: Build Oasis Docker image
        run: |
          git fetch --tags
          export BUILD_TAG=$(git describe --always)
          echo "Latest tag: $BUILD_TAG"
          docker build -t docker.pkg.github.com/oasisdefender/oasis/oasis:$BUILD_TAG .

      - name: Login to GitHub Packages
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ secrets.REPO_OASIS_ACCESS_TOKEN }}

      - name: Push Oasis Docker image to GitHub Packages
        run: |
          git fetch --tags
          export BUILD_TAG=$(git describe --always)
          echo "Latest tag: $BUILD_TAG"
          docker push docker.pkg.github.com/oasisdefender/oasis/oasis:$BUILD_TAG
